name: Pull Request Check

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Load Google Services File
        env:
          DATA: ${{ secrets.HA1_GOOGLE_SERVICES_JSON_BASE64 }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build
